In [36]:
# import load_iris function from scikit dataset module
from sklearn.datasets import load_iris

#importing numpy
import numpy as np

# saving 'bunch' object containing iris dataset and its attributes
iris = load_iris()

# store feature matrix in X
X = iris.data
# store the response vector
Y = iris.target


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
# # Printing the shape of X, shape is the dimensions of the matrix
# print (X.shape)

# # Printing the shape of Y
# print (Y.shape)

(150, 4)
(150,)


In [22]:
%%html
<t1><Strong>User guide:</Strong></t1>

<a href="https://scikit-learn.org/stable/user_guide.html">Click here!</a>


In [13]:
# Importing the class we are planning to use, in this case, it is KNeighborsClassifier
#  https://scikit-learn.org/stable/user_guide.html

from sklearn.neighbors import KNeighborsClassifier



In [25]:
# "Instationing" (making an instance of the object KNeighborsClassifier)

knn = KNeighborsClassifier(n_neighbors=1)

In [26]:
# For training the different kind of models we use .fit

knn.fit(X, Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [47]:
# For predicting a new result, we use .predict(*) and for * we use the new features
# In this case, the number of features is 4
new_X = np.array([[3, 5, 4, 2], [1, 1, 1, 1]])
knn.predict(new_X)

array([2, 0])